### ISSUE TITLE
关于福州大学mod。。。

### ISSUE THREAD

**Issue by wxyttty** [ZimoLoveShuang/auto-sign#2]
疑似虽然会过期，但好像是在几个中循环，昨天12点抓包的，今天凌晨过期，但10点半抓包又变回去了，

**Comment by ZimoLoveShuang** [comment]
事实上是只要你不**手动退出登陆**，就不会过期，但是需要发请求校验cookie，哦，我好像忘记写在`index.py`里面了，那就更新一下吧

**Comment by ZimoLoveShuang** [comment]
好像不对，我写了校验cookie，emmm

**Comment by wxyttty** [comment]
acw是不会过期，但mod会，昨天中午填表时抓包了，凌晨搞签到时发现cookie过期了，抓包发现mod变了，没有推出登录过

**Comment by ZimoLoveShuang** [comment]
是的，所以我代码里写了MOD_AUTH_CAS这个函数，来获取可能会更新的MOD_AUTH_CAS，现在看来是又失效了

**Comment by wxyttty** [comment]
但是如果是循环的，只要抓一次包就可以了，不需要函数了

**Comment by ZimoLoveShuang** [comment]
我猜 目前MOD_AUTH_CAS请求的响应 应该是404

**Comment by ZimoLoveShuang** [comment]
那你注释掉那个函数的调用再测试吧 虽然我觉得这方案不行

**Comment by wxyttty** [comment]
成功结果
https://fzu.cpdaily.com:443 "GET /wec-counselor-sign-apps/stu/mobile/index.html?signWid=252226&signInstanceWid=31132&from=push&timestamp
把更新mod的url在html?后加上signWid=252226&signInstanceWid=31132&from=push&（应该是签到任务的信息，每个人可能不同）就可以更新mod了，不能从登录获取就从任务或表获取

**Comment by ZimoLoveShuang** [comment]
将详细报文发给我，或者将账号借我测试一下看看，Q：461009747

**Comment by ZimoLoveShuang** [comment]
已经搞定，敬请期待更新。。稍后。。便同步到仓库
