### ISSUE TITLE
fzu签到失效

### ISSUE THREAD

**Issue by Mmahaha** [ZimoLoveShuang/auto-sign#3]
![IMG_20200826_092249](https://user-images.githubusercontent.com/42790539/91244000-d2b18900-e77d-11ea-9091-c6265730ff88.jpg)
如图，改了版本号也不行，不知道是不是请求体变了Ծ‸Ծ

**Comment by ZimoLoveShuang** [comment]
目前看起来更像是**个例**（ps：因为未有其他人反馈出现相同的情况），正常使用的话，脚本是**完全不用修改**的，只需要生成配置，然后修改配置就可以了；另外，你改版本号的话，密钥也要改，具体你可以看我另一个项目里面写的加解密算法，我应该在readme里面写了相关说明

**Comment by 924274383** [comment]
没有失效，今晚我还签到了

**Comment by Mmahaha** [comment]
> 没有失效，今晚我还签到了

确实可以，之前不知道啥问题了

**Comment by Ace-Monster** [comment]
请问fzu的同学你们的坐标能不能分享一下，我这里（坐标[119.198971, 26.063515]）显示不在签到范围内，尝试了很多个方案

**Comment by Mmahaha** [comment]
> 请问fzu的同学你们的坐标能不能分享一下，我这里（坐标[119.198971, 26.063515]）显示不在签到范围内，尝试了很多个方案

![Screenshot_2020-08-30-21-32-09-883_com guoshi httpcanary](https://user-images.githubusercontent.com/42790539/91791314-6e8f3900-ec45-11ea-88e0-22fcf6e587a5.jpg)
抓的32号楼的包，可以参考一下

**Comment by Ace-Monster** [comment]
> > 请问fzu的同学你们的坐标能不能分享一下，我这里（坐标[119.198971, 26.063515]）显示不在签到范围内，尝试了很多个方案
> 
> ![Screenshot_2020-08-30-21-32-09-883_com guoshi httpcanary](https://user-images.githubusercontent.com/42790539/91791314-6e8f3900-ec45-11ea-88e0-22fcf6e587a5.jpg)
> 抓的32号楼的包，可以参考一下

依旧显示不在范围内，以下是控制台log
```
python .\index.py
2020-09-01 11:27:36 {'tenantId': 'fzu', 'login-url': 'http://id.fzu.edu.cn/authserver/login?service=https%3A%2F%2Ffzu.cpdaily.com%2Fportal%2Flogin', 'host': 'fzu.cpdaily.com'}
2020-09-01 11:27:36 正在获取MOD_AUTH_CAS。。。
2020-09-01 11:27:36 获取MOD_AUTH_CAS成功。。。
{'signPhotoUrl': '', 'extraFieldItems': [{'extraFieldItemValue': '小于37.3度', 'extraFieldItemWid': 73583}, {'extraFieldItemValue': '否', 'extraFieldItemWid': 73585}], 'signInstanceWid': '45067', 'longitude': '119.198222', 'latitude': '26.056632', 'isMalposition': 0, 'abnormalReason': None, 'position': '中国福建省福州市闽侯县学府南路'}
2020-09-01 11:27:37 自动签到失败，原因是：不在签到范围内！
fail
```

**Comment by Mmahaha** [comment]
> > > 请问fzu的同学你们的坐标能不能分享一下，我这里（坐标[119.198971, 26.063515]）显示不在签到范围内，尝试了很多个方案
> > 
> > 
> > ![Screenshot_2020-08-30-21-32-09-883_com guoshi httpcanary](https://user-images.githubusercontent.com/42790539/91791314-6e8f3900-ec45-11ea-88e0-22fcf6e587a5.jpg)
> > 抓的32号楼的包，可以参考一下
> 
> 依旧显示不在范围内，以下是控制台log
> 
> ```
> python .\index.py
> 2020-09-01 11:27:36 {'tenantId': 'fzu', 'login-url': 'http://id.fzu.edu.cn/authserver/login?service=https%3A%2F%2Ffzu.cpdaily.com%2Fportal%2Flogin', 'host': 'fzu.cpdaily.com'}
> 2020-09-01 11:27:36 正在获取MOD_AUTH_CAS。。。
> 2020-09-01 11:27:36 获取MOD_AUTH_CAS成功。。。
> {'signPhotoUrl': '', 'extraFieldItems': [{'extraFieldItemValue': '小于37.3度', 'extraFieldItemWid': 73583}, {'extraFieldItemValue': '否', 'extraFieldItemWid': 73585}], 'signInstanceWid': '45067', 'longitude': '119.198222', 'latitude': '26.056632', 'isMalposition': 0, 'abnormalReason': None, 'position': '中国福建省福州市闽侯县学府南路'}
> 2020-09-01 11:27:37 自动签到失败，原因是：不在签到范围内！
> fail
> ```

可能签到范围不一样。。？ 安卓9以上用Magisk+Edxposed+trustmealready+httpcanary抓看看自己的坐标

**Comment by Ace-Monster** [comment]
> 可能签到范围不一样。。？ 安卓9以上用Magisk+Edxposed+trustmealready+httpcanary抓看看自己的坐标

签到范围是相同的，32号楼同样在软件所示签到范围内。事实上我定位到操场（即签到范围正中心）都无法成功签到

**Comment by Ace-Monster** [comment]
> 请问fzu的同学你们的坐标能不能分享一下，我这里（坐标[119.198971, 26.063515]）显示不在签到范围内，尝试了很多个方案

问题解决了，给之后出现问题的同学留个解决方法
可能是今日校园的问题，如果出现位置信息不对，可以尝试重新登录（使用login.py）
